# =========================================================================
# RANDOM FOREST: Classification and Regression — Flight Prices
# Adapted with Cross-Validation, Tuning, and Full Explainability (SHAP)
# With inverse transformation from logarithm to real scale (Euros) at the end
# =========================================================================

# --- 0. SETUP AND DATA LOADING ---
rm(list = ls())

# Automatic package installer (Bulletproof)
list.of.packages <- c(
  "randomForest", "ranger", "caret", "ggplot2", "dplyr",
  "reshape2", "vip", "pdp", "iml", "rpart", "rpart.plot", "future", "MLmetrics"
)
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages) > 0) install.packages(new.packages, dependencies = TRUE)
invisible(lapply(list.of.packages, require, character.only = TRUE))

# 1. Load the workspace generated by 10_Partition_Data.R
cat("\nLoading partitioned data from model_data.RData...\n")
load("data/interim/model_data.RData")

# 2. Ensure categorical variables are clean factors
train_df$airline   <- as.factor(train_df$airline)
train_df$nonStop   <- as.factor(train_df$nonStop)
train_df$economy_f <- as.factor(train_df$economy_f)

test_df$airline    <- as.factor(test_df$airline)
test_df$nonStop    <- as.factor(test_df$nonStop)
test_df$economy_f  <- as.factor(test_df$economy_f)

# Strict NA cleaning isolating variables (Avoids missing variable errors)
train_df_clean <- na.omit(train_df[, c("economy_f", pred_base)])
train_df_clean$economy_f <- droplevels(train_df_clean$economy_f)
test_df_clean  <- na.omit(test_df[, c("economy_f", pred_base)])


# =========================================================================
# 1. ADVANCED DESCRIPTIVE ANALYSIS
# =========================================================================
cat("      ADVANCED DESCRIPTIVE ANALYSIS\n")

cat("Train dimensions:", nrow(train_df_clean), "x", ncol(train_df_clean), "\n")
cat("Test dimensions :", nrow(test_df_clean),  "x", ncol(test_df_clean),  "\n\n")

# Class proportions (Stratification)
cat("Class proportions in Train:\n")
print(prop.table(table(train_df_clean$economy_f)))
cat("\nClass proportions in Test:\n")
print(prop.table(table(test_df_clean$economy_f)))

# Statistical summary of numerical variables
cat("\nDescriptive summary of numerical predictors:\n")
train_df_clean %>%
  select(where(is.numeric)) %>%
  summary() %>%
  print()

# Target variable distribution plot
p_dist_class <- ggplot(train_df_clean, aes(x = economy_f, fill = economy_f)) +
  geom_bar(show.legend = FALSE) +
  scale_fill_manual(values = c("Economy" = "#1a5fa8", "Premium" = "#c0392b")) +
  labs(title = "Target variable distribution (economy_f)", x = "Ticket Type", y = "Observations") +
  theme_minimal(base_size = 13)
print(p_dist_class)


# =========================================================================
# 2. RANDOM FOREST — CLASSIFICATION
# =========================================================================
cat("      RANDOM FOREST: CLASSIFICATION\n")

formula_class <- as.formula(paste("economy_f ~", paste(pred_base, collapse = " + ")))
cat("Classification formula:\n"); print(formula_class)

# --- 2A. Basic training ---
set.seed(1994)
rf_class <- randomForest(
  formula_class,
  data       = train_df_clean,
  ntree      = 300, 
  importance = TRUE
)
cat("\n--- BASIC MODEL TRAINED ---\n")
print(rf_class)


# --- 2B. CROSS-VALIDATION (Caret) ---
cat("\n--- RUNNING CROSS-VALIDATION (5-FOLD CV) ---\n")
library(caret)
trControl <- trainControl(
  method          = "cv",
  number          = 5,
  classProbs      = TRUE,
  summaryFunction = multiClassSummary,
  savePredictions = "final"
)

set.seed(1994)
rf_cv <- train(
  formula_class,
  data      = train_df_clean,
  method    = "rf",
  metric    = "Accuracy",
  trControl = trControl,
  ntree     = 150
)
print(rf_cv)

# Cross-validation plot
p_cv <- ggplot(rf_cv) + labs(title = "Random Forest Cross-Validation (caret)") + theme_minimal()
print(p_cv)


# --- 2C. HYPERPARAMETER TUNING (mtry) ---
cat("\n--- OPTIMIZING MTRY HYPERPARAMETER ---\n")
rf_grid <- expand.grid(mtry = c(2, 3, 4, 5))

set.seed(1994)
rf_tuned <- train(
  formula_class,
  data      = train_df_clean,
  method    = "rf",
  metric    = "Accuracy",
  trControl = trControl,
  tuneGrid  = rf_grid,
  ntree     = 150
)
print(rf_tuned)

# Tuning plot
p_tuned <- ggplot(rf_tuned) + labs(title = "mtry parameter optimization (caret)") + theme_minimal()
print(p_tuned)


# --- 2D. Predictions and Confusion Matrices (Train vs Test) ---
pred_train_class <- predict(rf_class, train_df_clean)
pred_test_class  <- predict(rf_class, test_df_clean)

cat("\n--- CONFUSION MATRIX (TRAIN) ---\n")
print(caret::confusionMatrix(pred_train_class, train_df_clean$economy_f))

cat("\n--- CONFUSION MATRIX (TEST) ---\n")
cm_test <- caret::confusionMatrix(pred_test_class, test_df_clean$economy_f)
print(cm_test)

# Confusion Matrix Plot (Test)
CM_df <- as.data.frame(cm_test$table)
p_cm_class <- ggplot(CM_df, aes(x = Reference, y = Prediction, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = Freq), size = 6, fontface = "bold", color = "white") +
  scale_fill_gradient(low = "#A8C8F9", high = "#1a5fa8") +
  labs(title = "Confusion Matrix — Random Forest (Test)", x = "Actual Class", y = "Prediction") +
  theme_minimal(base_size = 13)
print(p_cm_class)


# =========================================================================
# 3. VARIABLE IMPORTANCE
# =========================================================================
cat("      VARIABLE IMPORTANCE\n")

# 3A. Impurity Importance (Gini)
imp_class <- as.data.frame(rf_class$importance)
imp_class$Variable <- rownames(imp_class)
imp_class_top <- imp_class %>%
  arrange(desc(MeanDecreaseGini)) %>%
  mutate(Variable = reorder(Variable, MeanDecreaseGini))

p_imp_class <- ggplot(imp_class_top, aes(x = Variable, y = MeanDecreaseGini, fill = MeanDecreaseGini)) +
  geom_col(show.legend = FALSE) +
  scale_fill_gradient(low = "#A8C8F9", high = "#1a5fa8") +
  coord_flip() +
  labs(title = "Variable Importance — Mean Decrease Gini", x = NULL, y = "Gini") +
  theme_minimal(base_size = 13)
print(p_imp_class)

# 3B. Permutation Importance (Via Ranger)
cat("\nCalculating Permutation Importance with Ranger...\n")
set.seed(1994)
rf_ranger <- ranger(
  formula_class,
  data       = train_df_clean,
  num.trees  = 300,
  importance = "permutation"
)
p_imp_perm <- vip(rf_ranger) + labs(title = "Permutation Importance (Ranger)") + theme_minimal()
print(p_imp_perm)


# =========================================================================
# 4. FORESTRY TREE EXTRACTION AND SURROGATE TREE
# =========================================================================
cat("      TREE EXTRACTION AND INTERPRETATION\n")

# 4A. Structural extraction of an internal forest tree
cat("\nInternal structure of Tree number 1 from Random Forest:\n")
arbol_1 <- getTree(rf_class, k = 1, labelVar = TRUE)
print(head(arbol_1, 15))

# 4B. Surrogate tree with rpart for simple graphical representation
set.seed(1994)
arbol_aux_class <- rpart(
  formula_class,
  data    = train_df_clean,
  method  = "class",
  control = rpart.control(maxdepth = 3, minbucket = 10, cp = 0.0001)
)
rpart.plot(arbol_aux_class, main = "Surrogate Tree for Visual Interpretation", type = 3, extra = 104, fallen.leaves = TRUE, shadow.col = "gray")


# =========================================================================
# 5. PARTIAL DEPENDENCE PLOTS (PDP) AND SHAP VALUES
# =========================================================================
cat("      INTERPRETABILITY: PDP AND SHAP\n")

# 5A. Partial Dependence Plot
p_pdp <- partial(rf_class, pred.var = "travelDistance", train = train_df_clean, which.class = "Economy", prob = TRUE)
print(autoplot(p_pdp) + labs(title = "PDP: Effect of travelDistance on Economy probability", y = "Mean Probability"))

# 5B. SHAP Preparation (Reduced sample for RAM performance)
future::plan(future::sequential)
options(future.globals.maxSize = 2 * 1024^3)

set.seed(1994)
X_train_class <- train_df_clean %>% select(all_of(pred_base))
y_train_class <- train_df_clean$economy_f

idx_shap <- sample(seq_len(nrow(X_train_class)), size = min(300, nrow(X_train_class)))
X_shap   <- X_train_class[idx_shap, , drop = FALSE]
y_shap   <- y_train_class[idx_shap]

predict_fun_economy <- function(model, newdata) { 
  predict(model, newdata, type = "prob")[, "Economy"] 
}

predictor_economy <- Predictor$new(
  model = rf_class, data = X_shap, y = as.numeric(y_shap == "Economy"),
  predict.function = predict_fun_economy, type = "prob"
)

# 5C. Global SHAP
cat("\nCalculating Global Importance (FeatureImp) based on iml...\n")
set.seed(1994)
effect_global <- FeatureImp$new(predictor_economy, loss = "ce", n.repetitions = 3)
print(plot(effect_global) + labs(title = "Global Importance (Permutation Loss) for Economy class"))

# 5D. Local SHAP
cat("\nCalculating local SHAP for the first Test observation...\n")
set.seed(1994)
shap_obs_class <- Shapley$new(predictor_economy, x.interest = test_df_clean[1, pred_base, drop = FALSE], sample.size = 100)
print(plot(shap_obs_class) + labs(title = "Local SHAP for Test[1] observation — Economy Class"))


# =========================================================================
# 6. RANDOM FOREST — REGRESSION (log_price)
# =========================================================================
cat("      RANDOM FOREST: REGRESSION (log_price)\n")

pred_reg <- c(pred_base, "economy_f")
formula_reg <- as.formula(paste("log_price ~", paste(pred_reg, collapse = " + ")))
cat("Regression formula:\n"); print(formula_reg)

# Train data preparation for Regression
train_df_reg <- na.omit(train_df[, c("log_price", pred_reg)])

set.seed(1994)
rf_reg <- randomForest(
  formula_reg,
  data       = train_df_reg,
  ntree      = 300,
  importance = TRUE
)

cat("\n--- TRAINED REGRESSION MODEL ---\n")
print(rf_reg)

# Classic regression importance plot (%IncMSE and MeanDecreaseAccuracy)
varImpPlot(rf_reg, main = "Variable Importance (Random Forest Regression)")

# --- 6B. PREDICTION AND INVERSE CONVERSION TO REAL EUROS ---
cat("      PREDICTIONS AND EVALUATION IN REAL SCALE (EUROS)\n")

# Isolate the test set for regression including the untransformed real price (totalPrice)
test_df_reg <- na.omit(test_df[, c("log_price", "totalPrice", pred_reg)])

# 1. Make predictions on the Test Set (Returns values in logarithmic scale)
pred_log <- predict(rf_reg, test_df_reg)

# 2. INVERSE TRANSFORMATION: Apply exponential to return to Euros (€)
pred_euros <- exp(pred_log)

# 3. Consolidate results in a comparative table
resultados_finales <- data.frame(
  Actual_Price_Euros = test_df_reg$totalPrice,
  Predicted_Euros    = round(pred_euros, 2),
  Absolute_Difference = round(abs(test_df_reg$totalPrice - pred_euros), 2)
)

cat("Sample of the first 10 predictions converted back to Euros:\n")
print(head(resultados_finales, 10))

# 4. Calculate error metrics in the real monetary scale using MLmetrics
mae_euros  <- MLmetrics::MAE(y_pred = pred_euros, y_true = test_df_reg$totalPrice)
rmse_euros <- MLmetrics::RMSE(y_pred = pred_euros, y_true = test_df_reg$totalPrice)
mape_euros <- MLmetrics::MAPE(y_pred = pred_euros, y_true = test_df_reg$totalPrice)

cat("\nPerformance Metrics in Real Scale (Euros):\n")
cat("-> MAE (Mean Absolute Error):", round(mae_euros, 2), "€\n")
cat("-> RMSE (Root Mean Squared Error):", round(rmse_euros, 2), "€\n")
cat("-> MAPE (Mean Absolute Percentage Error):", round(mape_euros * 100, 2), "%\n")