---
title: "Basic initial univariate descriptive statistic of raw variables - Flight Prices"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

list.of.packages <- c("ggplot2", "dplyr", "visdat", "naniar", "DataExplorer",
                      "VIM", "tidyr", "knitr", "gridExtra")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if (length(new.packages) > 0) install.packages(new.packages, repos = "https://cloud.r-project.org")
lapply(list.of.packages, require, character.only = TRUE)
```

```{r carga-limpieza}
if (!requireNamespace("here", quietly = TRUE)) install.packages("here")

input_path <- here::here("data", "interim", "flightprices_interim.rds")

dd <- readRDS(input_path)
```

## General Statistical Overview

```{r resumen-general}

inventario <- data.frame(
  Variable = names(dd),
  Type     = sapply(dd, function(x) paste(class(x), collapse = "/")),
  NAs  = sapply(dd, function(x) sum(is.na(x)))
)

kable(inventario, caption = "Information of all variables")

df_num <- dd %>% select(where(is.numeric))

resumen_num <- data.frame(
  Variable = names(df_num),
  Min      = sapply(df_num, function(x) min(x, na.rm = TRUE)),
  Median   = sapply(df_num, function(x) median(x, na.rm = TRUE)),
  Mean     = sapply(df_num, function(x) mean(x, na.rm = TRUE)),
  Max      = sapply(df_num, function(x) max(x, na.rm = TRUE)),
  SD       = sapply(df_num, function(x) sd(x, na.rm = TRUE)),
  CV       = sapply(df_num, function(x) sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE))
)

kable(resumen_num, digits = 2, caption = "Statistical Summary of Numeric Variables")


```

## Univariate analysis

```{r analisis-univariante, results='asis', fig.width=10, fig.height=4}
analisis <- function(X, nom) {
  cat("\n\n### Variable:", nom, "\n\n")
  
  # NUMÉRICO
  if (is.numeric(X)) {
   # cat("**Mean** =", round(mean(X, na.rm = TRUE), 2),
   #     "| **SD** =", round(sd(X, na.rm = TRUE), 2),
   #     "| **CV** =", round(sd(X, na.rm = TRUE) / mean(X, na.rm = TRUE), 4), "\n\n")
    
    p1 <- ggplot(data.frame(x = X), aes(x = x)) +
      geom_histogram(fill = "steelblue", color = "white", bins = 30) +
      labs(title = paste("Distribution of", nom), x = nom, y = "Frequency") +
      theme_minimal()
    
    p2 <- ggplot(data.frame(x = X), aes(y = x)) +
      geom_boxplot(fill = "orange", alpha = 0.7) +
      labs(title = paste("Boxplot of", nom), y = nom) +
      theme_minimal()
    
    print(p1)
    print(p2)
    
 # CATEGÓRICO
  } else if (is.factor(X) || is.character(X) || is.logical(X)) {
    if(is.logical(X)) X <- as.factor(X) 
    frecs <- table(X, useNA = "ifany")
    prop  <- round(prop.table(frecs) * 100, 2)
    
    nombres_categorias <- names(frecs)
    nombres_categorias[is.na(nombres_categorias)] <- "NAs"
    
    tab <- data.frame(
      Category = nombres_categorias,
      Frequency = as.vector(frecs), 
      Percentage = as.vector(prop)
    )
    
    print(kable(tab, caption = paste("Frequencies of", nom), row.names = FALSE))
    
    df_plot <- as.data.frame(frecs)
    colnames(df_plot) <- c("Clase", "Freq")
    df_plot$Clase <- as.character(df_plot$Clase)
    df_plot$Clase[is.na(df_plot$Clase)] <- "NA"
    
    p_bar <- ggplot(df_plot, aes(x = reorder(Clase, -Freq), y = Freq, fill = Clase)) +
      geom_bar(stat = "identity") +
      labs(title = paste("Frequencies of", nom), x = nom, y = "N") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      guides(fill = "none")
    
    print(p_bar)
    
  # FECHA
 } else if (inherits(X, "Date") || inherits(X, "POSIXct")) {
    
    sum_x <- summary(X)
    df_temp <- as.data.frame(as.list(as.character(sum_x)))
    colnames(df_temp) <- names(sum_x)
    print(kable(df_temp))
    
    # Histogram
    p_hist <- ggplot(data.frame(x = X), aes(x = x)) +
      geom_histogram(fill = "darkseagreen", color = "white", bins = 20) +
      labs(title = paste("Temporal evolution:", nom), x = "Date", y = "Flights") +
      theme_minimal()
    
    #print(p_date)
    p_box <- ggplot(data.frame(x = X), aes(y = x, x = "")) +
      geom_boxplot(fill = "darkseagreen", alpha = 0.5) +
      labs(title = paste("Boxplot of:", nom), y = "Date", x = "") +
      theme_minimal() +
      coord_flip()
    
    grid.arrange(p_hist, p_box, ncol = 2)
    
  }
  
  cat("\n\n---\n\n")
}

for (col_name in names(dd)) {
  analisis(dd[[col_name]], col_name)
}
```
